<?php
declare(strict_types=1);

require_once __DIR__ . '/contact-service.php';

const ADMIN_SESSION_TIMEOUT = 1800;   // seconds of inactivity before logout
const LOGIN_MAX_ATTEMPTS = 5;         // failed logins allowed...
const LOGIN_WINDOW = 900;             // ...per visitor within this many seconds
const MESSAGES_PER_PAGE = 20;

/* ---------- authentication ---------- */

// credentials live in php/admin-config.php, generated by php/create-admin.php and never committed
function admin_credentials(): ?array
{
    $file = __DIR__ . '/admin-config.php';
    if (!is_file($file)) {
        return null;
    }
    $credentials = require $file;
    return is_array($credentials) && !empty($credentials['username']) && !empty($credentials['password_hash'])
        ? $credentials
        : null;
}

function is_admin(): bool
{
    if (empty($_SESSION['admin_user'])) {
        return false;
    }
    if (time() - ($_SESSION['admin_seen'] ?? 0) > ADMIN_SESSION_TIMEOUT) {
        admin_logout();
        return false;
    }
    $_SESSION['admin_seen'] = time();
    return true;
}

function login_attempts_table(PDO $pdo): void
{
    $pdo->exec('CREATE TABLE IF NOT EXISTS login_attempts (ip_hash TEXT NOT NULL, attempted_at INTEGER NOT NULL)');
}

function login_is_locked(PDO $pdo, string $ipHash): bool
{
    $statement = $pdo->prepare('SELECT COUNT(*) FROM login_attempts WHERE ip_hash = :ip AND attempted_at > :since');
    $statement->execute([':ip' => $ipHash, ':since' => time() - LOGIN_WINDOW]);
    return (int) $statement->fetchColumn() >= LOGIN_MAX_ATTEMPTS;
}

function record_failed_login(PDO $pdo, string $ipHash): void
{
    $pdo->prepare('DELETE FROM login_attempts WHERE attempted_at <= :since')->execute([':since' => time() - LOGIN_WINDOW]);
    $pdo->prepare('INSERT INTO login_attempts (ip_hash, attempted_at) VALUES (:ip, :now)')
        ->execute([':ip' => $ipHash, ':now' => time()]);
}

/**
 * Returns true on success, or the error message to display.
 */
function admin_login(PDO $pdo, string $username, string $password): string|true
{
    $credentials = admin_credentials();
    if ($credentials === null) {
        return 'Aucun compte administrateur. Lancez : php php/create-admin.php <identifiant> <mot-de-passe>';
    }

    login_attempts_table($pdo);
    $ipHash = visitor_hash();
    if (login_is_locked($pdo, $ipHash)) {
        return 'Trop de tentatives. Réessayez dans 15 minutes.';
    }

    // password_verify always runs so a wrong username takes as long as a wrong password
    $passwordOk = password_verify($password, $credentials['password_hash']);
    if (!hash_equals($credentials['username'], $username) || !$passwordOk) {
        record_failed_login($pdo, $ipHash);
        return 'Identifiant ou mot de passe incorrect.';
    }

    $pdo->prepare('DELETE FROM login_attempts WHERE ip_hash = :ip')->execute([':ip' => $ipHash]);
    // new session id + new CSRF token so nothing from before the login can be reused
    session_regenerate_id(true);
    unset($_SESSION['csrf_token']);
    $_SESSION['admin_user'] = $username;
    $_SESSION['admin_seen'] = time();
    return true;
}

function admin_logout(): void
{
    unset($_SESSION['admin_user'], $_SESSION['admin_seen'], $_SESSION['csrf_token']);
    session_regenerate_id(true);
}

/* ---------- messages ---------- */

function count_messages(PDO $pdo): array
{
    $row = $pdo->query('SELECT COUNT(*) AS total, COALESCE(SUM(read_at IS NULL), 0) AS unread FROM messages')->fetch();
    return ['total' => (int) $row['total'], 'unread' => (int) $row['unread']];
}

function list_messages(PDO $pdo, bool $unreadOnly, int $page): array
{
    $where = $unreadOnly ? 'WHERE read_at IS NULL' : '';
    $statement = $pdo->prepare("SELECT id, name, email, subject, message, mailed, read_at, created_at
        FROM messages $where ORDER BY created_at DESC, id DESC LIMIT :limit OFFSET :offset");
    $statement->bindValue(':limit', MESSAGES_PER_PAGE, PDO::PARAM_INT);
    $statement->bindValue(':offset', ($page - 1) * MESSAGES_PER_PAGE, PDO::PARAM_INT);
    $statement->execute();
    return $statement->fetchAll();
}

function set_message_read(PDO $pdo, int $id, bool $read): void
{
    $pdo->prepare('UPDATE messages SET read_at = :readAt WHERE id = :id')
        ->execute([':readAt' => $read ? time() : null, ':id' => $id]);
}

function delete_message(PDO $pdo, int $id): void
{
    $pdo->prepare('DELETE FROM messages WHERE id = :id')->execute([':id' => $id]);
}
